### ISSUE TITLE
Release Matomo 4.0.0

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#14601]
#### Work on Beta cycle, towards Release Candidate 1:

- [x]    Beta release cycle has started with the first beta release https://github.com/matomo-org/matomo/issues/16165
- [x] **Keep track of releases notes/ any important changes in this wiki page: https://github.com/matomo-org/matomo/wiki/Matomo-4.0.0-release-notes**
- [x] Make a new release of PHP SDK Tracker (~there is a 4.x-dev branch there~ 4.x-dev merged into master, 3.0.0 released and 4.x-dev matomo using it)
- [x] Check [this list of Pull requests all Matomo repositories](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Apr+org%3Amatomo-org+org%3Ainnocraft+milestone%3A%22Current+sprint%22+), where the milestone is set to `Current sprint`
- [x] Triage [all PRs](https://github.com/pulls?utf8=%E2%9C%93&q=is%3Aopen+is%3Apr+org%3Amatomo-org+org%3Ainnocraft+no%3Amilestone) not scheduled yet, or close (see also [issues without milestone](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+org%3Amatomo-org+org%3Ainnocraft+no%3Amilestone))
- [x] Check all 3.x and 4.x branches include the same changes in all plugins
- [x] Check each plugin has a release for the most recent changes in 4.x-dev
- [ ]   Tag a new release for `matomo-org/referrer-spam-blacklist` and `matomo-org/searchengine-and-social-list`
- [x]  Fetch our latest and greatest home-made libraries with `composer update matomo-org/referrer-spam-blacklist matomo-org/searchengine-and-social-list matomo-org/matomo-php-tracker matomo-org/component-network,matomo-org/component-ini,matomo-org/component-decompress,matomo-org/component-cache`
- [x]    Fetch the latest composer libraries for all with `composer update`
- [x]   Up to date submodules
- [x]  Make [CI builds](https://travis-ci.com/matomo-org/) of our official plugins `matomo-org/plugin-*` all green 
- [x]  Tag the RC candidate 
- [x]   Check that the build is green
- [x]   [Package & release](https://github.com/matomo-org/matomo-package#core-matomo-package) the Release Candidate
- [x]   Post sticky thread in forum [about RC](https://forum.matomo.org/t/matomo-3-10-0-release-candidate-release-help-needed/33243) 
- [ ] Let translators know about the new RC by [posting an announcement here](https://www.transifex.com/matomo/matomo/announcements/)
- [x]   inform RC release on social media 
- [x]   update tag manager submodule

#### Look for issues:
- [x]    Forum support: regularly check all posts in [Support & Bugs forum](http://forum.matomo.org/c/support-bugs)
- [x]   Forum General questions: look for bugs & regressions in [General questions forum](http://forum.matomo.org/c/general-questions) 
- [ ]  Backlog grooming (Matomo core): [check issues without milestone](https://github.com/matomo-org/matomo/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+no%3Amilestone) and [PRs](https://github.com/matomo-org/matomo/pulls?q=is%3Apr+is%3Aopen+no%3Amilestone) if any one should be fixed in this release 
- [ ]  Check [this list of issues across all Matomo repositories](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+org%3Amatomo-org+org%3Ainnocraft+milestone%3A%22Current+sprint%22+), where the milestone is set to `Current sprint` 

#### The final checks before the stable release:
- [x]   Release candidate cycle (at least 1 week cycle)
- [ ]  Fix all remaining issues in the milestone
- [x] All open source [plugins builds](https://travis-ci.org/matomo-org/) are green on `master` with latest RC
- [x] Plugins that needed a version bump are now released on the marketplace
- [ ]   Synchronise translations from transifex 
- [ ]   Submodules are up to date
- [x] triple check 3.14.1 changes are in 4.x such as https://github.com/matomo-org/matomo/pull/16226 
- [x] Announce Long Term Support version refs #15920

#### Prepare the [Changelog entry](http://matomo.org/changelog/):  
  - [x]  Mark that the release has a major DB upgrade
  - [x] Ensure that [all PRs merged into the 4.x-dev base branch but that don't have a 4.x milestone set yet](https://github.com/matomo-org/matomo/pulls?page=3&q=is%3Apr+base%3A4.x-dev+-milestone%3A%224.0.0-RC%22+-milestone%3A%224.0.0%22+is%3Aclosed) will be set with a 4.0.0 milestone 
  - [x]   Use [our github changelog generator](https://github.com/matomo-org/github-changelog-generator) to generate the changelog [using this `config.js`](https://github.com/matomo-org/github-changelog-generator#sample-configjs-file). **Set milestones to ignore to `3.*`and look at all closed issues since Jan 14th 2020 (first commit to 4.x-dev was on Jan 14th).** 
  - [x]   Add to changelog any new issues or FAQ added since first RC
  - [x]   Add to changelog the security issues fixed, if any (eg. credit #115 #114) 
  - [x]  Do not publish publicly the changelog yet. This also ensures security issues are not publicly visible until the stable release.
  - [x]   Change changelog published date to the release day
 - [ ] Make it clear/visible that it's important to take a DB backup before the upgrade 

#### Check the developer changelog is complete, by looking over each issue:
  - [x]  is this issue relevant to developers? let's mention it in the [Developer changelog](http://developer.matomo.org/changelog)
  - [x]  is this issue's title descriptive and useful to people scanning our changelog? 
  - [x]  are the right labels applied to the issue? (issues tagged with labels such as `Bug`, `Enhancement`, `Major` are grouped together in the changelog)
 
#### Add any new features to the features page

 - [x] Identify new features and list them on the [Matomo features](https://matomo.org/features/) page.

#### Merge 3.x-dev branch into master:
  - [x]   In https://github.com/matomo-org/matomo/settings get an admin to enable "Merge buttons > Allow merge commits"
  - [x]   Create a Pull request to merge 3.x-dev into master, by clicking on "Merge Pull request > **Create a merge commit**" (_not_ "Squash & merge")
  - [x]   In https://github.com/matomo-org/matomo/settings get an admin to disable "Merge buttons > Allow merge commits"

#### :boom: Release :rocket: 
- [x]   Close milestone on Github
- [x] Release publicly the new stable version by running `./scripts/build-package.sh 3.x.y` from [here](https://github.com/matomo-org/matomo-package) and waiting 5 minutes
- [x]   In Github release we write 

```
## [Matomo 3.3.0 Changelog](https://matomo.org/changelog/matomo-3-3-0/)

This Github download (below) is only meant for developers and it will require extra work to install it. 
 * Latest stable production release can be found at https://matomo.org/download/ ([learn more](https://matomo.org/docs/installation/)) (recommended)
 * Beta and Release Candidates releases can be found at https://builds.matomo.org/ ([learn more](http://matomo.org/faq/how-to-update/faq_159/))

## List of XXX tickets closed
```
- [x] Add the list of tickets closed from the changelog into the Github release
- [x]  Take screenshots of new features + draft a blog post showcasing what's new 
- [x] Create this 'Release Matomo 3.*' issue in the next release milestone

**Comment by tsteur** [comment]
@mattab I suppose component-cache will be automatically updated to the latest 1.0.3 version? https://github.com/matomo-org/component-cache/pull/20/files Not seeing it in the RC so not sure

**Comment by tsteur** [comment]
created https://github.com/matomo-org/matomo/pull/14683 should be in the release

**Comment by mattab** [comment]
Note: We’ll need to release Matomo 4 at the latest on November 17th. Reason: PHP 8 will be released on November 26th and people will be updating to PHP 8… 

So we aim to release RC by around end of october and stable release by around Nov 17th

**Comment by mattab** [comment]
we also need to announce the Long Term Support. Could we maybe reuse/redirect this old post with up to date info? (it is linked from the FAQ https://matomo.org/faq/new-to-piwik/faq_18926/):  https://matomo.org/blog/2016/01/announcing-long-term-support-in-piwik-2-the-analytics-platform-for-your-mission-critical-projects/

**Comment by mattab** [comment]
Matomo 4.0.0-rc1 is released! https://builds.matomo.org/piwik-4.0.0-rc1.zip

**Comment by mattab** [comment]
Matomo 4.0.0-rc2 is released. https://builds.matomo.org/piwik-4.0.0-rc2.zip

**Comment by mattab** [comment]
Matomo 4.0.0-rc5 is released.  http://builds.matomo.org/piwik-4.0.0-rc5.zip

Stable release scheduled for Monday/Tuesday next week :rocket:

**Comment by mattab** [comment]
All done, great job everyone :100: :volcano:
