### ISSUE TITLE
Piwik to become official GNU package

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#5276]
Piwik was asked by Richard Stallman and FSF, whether we would like to make Piwik a GNU package:

```

[[[ To any NSA and FBI agents reading my email: please consider    ]]]
[[[ whether defending the US Constitution against all enemies,     ]]]
[[[ foreign or domestic, requires you to follow Snowden's example. ]]]

Would you like to make Piwik a GNU package?

```

See below comments for more info.

**Steps**

General changes to Piwik:
- [x] use the words `Free / Libre software` instead of `Open source software`
- [x] make Piwik declare the JS code as LibreJS compatible #3770
- [x] show GNU/Linux instead of Linux https://github.com/piwik/device-detector/issues/14 
- [x] clearly document all library licenses used by Piwik in: https://github.com/piwik/piwik/blob/master/LEGALNOTICE

**Improve Privacy in Piwik**
issues suggested by FSF Richard Stallman that we think would help improve Privacy by default in Piwik:
- [x] Do not store Accept-language full string, only store detected language #5365 
- [x] Enable IP anonimisation by default, let users disable anonymisation during Piwik installation #5052
- [ ] When IP anonimisation is enabled, hash the IP address in a way that prevents fingerprinting #5907 
- [ ]  Generate a Disclaimer explaining analytics data tracking and privacy #3725 
- [ ] Create a Privacy Seal #6173

**Comment by mattab** [comment]
This won't happen

**Comment by mackuba** [comment]
Hey,

if you gave up on this idea, could you consider reverting https://github.com/matomo-org/device-detector/issues/14? I'd wager that a vast majority of people who use Matomo don't use the term "GNU/Linux" personally and might even be confused by it...

**Comment by Findus23** [comment]
@mackuba Personally I have to disagree. Device Detector doesn't detect the kernel itself, but the userspace around GNU and all other software installed. And for people who get confused by this detail there is a icon next to it that shows them that this is the "Linux" they know. 
![grafik](https://user-images.githubusercontent.com/6266037/51764216-ea71e880-20d4-11e9-8928-fdafc6bff911.png)

But this isn't really a strong opinion (after all the user agent just says `Linux x86_64`) and the last thing I want is this to end up as a huge fight.

**Comment by sgiehl** [comment]
I don't have a opinion on that at all. But it seem to be an ongoing discussion which name is "better". It even has it's own wikipedia page: https://en.wikipedia.org/wiki/GNU/Linux_naming_controversy
