### ISSUE TITLE
Building the best Enterprise Analytics Platform 

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo#8920]
At Piwik our mission is to help individuals and organisations keep full control of their data. Piwik is becoming more and more popular with medium businesses, big companies, corporations, governments. 

In this issue, we would like to **gather all the requirements to meet so that Piwik can become the best [Enterprise Analytics](http://piwik.org/enterprise-analytics/) platform.**

Please leave a comment with your suggestion or ideally: a link to an existing github issue.

**Comment by mattab** [comment]
Piwik is an Enterprise platform and already used in many very large companies and governments. We've already made amazing progress in the last two years... Many issues we fixed and implemented were requested & sponsored by some of our [PRO Enterprise](http://piwik.pro/enterprise) clients. 

Our work is not finished though and there are still important features to build to make Piwik awesome for Enterprise users:

 * [x] Introducing Long Term Support #8546 (decided at our [2015 community meetup](https://piwik.org/blog/2015/08/notes-piwik-community-meetup-2015/))
 * [ ] Implement "Content Security Policy" (CSP)
 * [ ] Show all personal email reports, custom alerts of all sites at once, not only the ones of the current selected site  #7076 
 * [ ] Super Users should be able to list all segments #6766
 * [ ]  Admin role should be able to create segments visible to all users having access to this website #6844 
 * [ ] Improve User Management and assigning permissions to users #6187 
 * [ ] Customizable columns in All Websites Dashboard #5150

**Comment by tsteur** [comment]
* User groups / roles / ACL. Let a superuser/admin define what a user is allowed to do in Piwik, move multiple users into one group, assign user permissions like view or admin to a group of websites, ... Management for 1000 users with 1000 different websites should be easy. When there's a new employee it should be easy to give that user the right permissions for the right websites (the websites that department is allowed to see and manage) in seconds with one or two clicks.

* Pretty much all tracking and archiving related settings from `global.ini.php`, also some settings in the UI should be customizable for each site and for a group of sites.

* Various single sign on connectors, eg Jira, Salesforce, ...

* Deployment of Piwik to a multi server architecture should be as easy as possible, ideally "out of the box". This also means using Redis for caches, etc.

* Sharing dashboards

* Site and "group of sites" specific Dashboards (eg all sites in group "Marketing" would have the same dashboards)

* Role specific dashboards (eg a user role SEO would always see the SEO dashboards on all sites )

* More advanced email reports, at least better, professional looking ones

I'm sure there's much more

**Comment by MagicFab** [comment]
* GNU/Linux packaging in main Debian repository, as part of the distribution (see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=448532) and RHEL
* Easy + free SSL setup (see https://letsencrypt.org/)
* 2FA in core/default activated plugins (currently an extra plugin, see https://github.com/sgiehl/piwik-plugin-GoogleAuthenticator)
* Connectors to various monitoring and status tools (such as https://cachethq.io/)
* Internal Piwik audit+reporting capability (users activity log)
* Standards compliance (HIPAA, others?)

**Comment by gaumondp** [comment]
I don't need it myself and I hate to write it but : 

* Multiple DB support *is* an important enterprise go/no-go feature for many.

**Comment by tsteur** [comment]
* Block users for X minutes or an hour after Y unsuccessful logins, 
* 2FA in core :+1: 
* token_auth should no longer be able to use as login and to authenticate, instead proper API authentication, eg oAuth etc.
* salted, hashed passwords in DB that do not depend on username + password

In general platform should be more secure if one wants to use it in Enterprise

**Comment by tsteur** [comment]
Actually some or pretty much all of the Piwik PRO plugins https://piwik.pro/plugins/ would be useful to have in Piwik to build an analytics platform for enterprise. They conflict a little with our mission statement of Piwik.

**Comment by tsteur** [comment]
> salted, hashed passwords in DB that do not depend on username + password
> token_auth should no longer be able to use as login and to authenticate, instead proper API authentication, eg oAuth etc.

Also we should not store `token_auth` in database and especially not in plain text

**Comment by tsteur** [comment]
* Improve Piwik's sharing capabilities: Let a user share reports #9351
* Improve print version of Piwik #9347

**Comment by RMastop** [comment]
Send email to notify a new user after creating their account. In this email we can write them about the password reset function (or if some other authentication is used let them know about this).

**Comment by tsteur** [comment]
:+1: maybe we should create a new issue for this as well in case we don't have one yet as I find it almost mandatory and always wondered why we haven't been sending mails already for new accounts

**Comment by RMastop** [comment]
Fully separate tracking from reporting. For security and performance reasons.

**Comment by tsteur** [comment]
> Fully separate tracking from reporting. For security and performance reasons.

I also want to have this for technical reasons. It will be much easier to maintain and to contribute when having these things separated. Each project will be smaller and more clear. Also they will be usable independently. Meaning someone can use tracking feature, but build different custom reporting.

**Comment by hpvd** [comment]
most wanted "unvisible technical" feature:
 "keep raw data"

to be able to
- reprocess them afterwards again e.g. https://github.com/piwik/piwik/issues/8955
- make thinks like combining data of different sources easier (or even possible) https://github.com/piwik/piwik/issues/9665
- show/hide (include exclude) special types of visits (bots, deteleted ones etc...)
https://github.com/piwik/piwik/issues/9205 https://github.com/piwik/piwik/issues/9067

see also https://github.com/piwik/piwik/issues/8955#issuecomment-178479720

**Comment by hpvd** [comment]
most wanted "field of features" to be enhanced
**everything with ecommerce** (simply search for it within issues)

reasona:
- large group of users
- group of users who has to like piwik "owner ship of data" by default (because of laws in several countries)
- group of users having money to spent and are willing to do so *for good solutions*
(imortant for making piwik future prrof see comments in https://github.com/piwik/piwik/issues/9169)

**Comment by tsteur** [comment]
Site specific dashboards

**Comment by mattab** [comment]
Thanks everyone for your participation in this issue! We appreciate your input. This issue covers a lot of ground, and it's a bit too broad for us to tackle effectively as is. So, we're going to close it for now.

But don't let this stop you! If you've got specific ideas or improvements related to this topic, feel free to open new issues for each one. That way, we can dive into them in more detail.
